### ISSUE TITLE
Support running on k8s with ResourceQuotas

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/secret-operator#263]
Part of https://github.com/stackabletech/issues/issues/368

A workaround is
```
cat > secret-operator-daemonset.patch << 'EOF'
spec:
  template:
    spec:
      containers:
      - name: external-provisioner
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
      - name: node-driver-registrar
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
EOF
kubectl patch daemonset secret-operator-daemonset --patch-file secret-operator-daemonset.patch
```
