### ISSUE TITLE
Allow configuring CA cert lifetime and refresh interval

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/secret-operator#354]
Extracted from https://github.com/stackabletech/secret-operator/pull/350#discussion_r1469442628

This might be a breaking change for https://github.com/stackabletech/issues/issues/504

**Comment by nightkr** [comment]
This shouldn't be breaking, since we can default to the current values.

**Comment by sbernauer** [comment]
Maybe, but maybe we also want to move all that stuff under a common key, such as `management`. How knows :D
```
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: default
        # Change
        autoGenerate: true
        # to something like
        management:
          enabled: true
          caCertLifetime: 2y
          caCertRenewalThreshold: 1y
```
