### ISSUE TITLE
Kerberos Principal Checking is overly restrictive (forbids underscore).

### ISSUE THREAD

**Issue by fetzerms** [stackabletech/secret-operator#562]
### Affected Stackable version

24.11

### Current and expected behavior

We are currently checking integration with active directory. By convention, our privileged users have a underscore in their name. Stackable rejects our admin principal. This is caused by the code at: https://github.com/stackabletech/secret-operator/blob/main/rust/operator-binary/src/crd.rs#L345 

Sample SecretClass that shows the issue:

```yaml
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: admin-credentials-class
spec:
  backend:
    kerberosKeytab:
      realmName: <snip>
      kdc: <snip>
      admin:
        activeDirectory:
          ldapServer: <snip>
          ldapTlsCaSecret:
            namespace: default
            name: secret-operator-ad-ca
          passwordCacheSecret:
            namespace: default
            name: secret-operator-ad-passwords
          userDistinguishedName: <snip>
          schemaDistinguishedName: <snip>
      adminKeytabSecret:
        namespace: default
        name: secret-operator-keytab
      adminPrincipal: my_user@<snip>
```

### Possible solution

Include underscore here: https://github.com/stackabletech/secret-operator/blob/main/rust/operator-binary/src/crd.rs#L345 or change from allowlist to blocklist.

### Would you like to work on fixing this bug?

no
