### ISSUE TITLE
Deploy additional CAs with the autoTls backend

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/secret-operator#570]
# Description

It should be possible to deploy additional CAs with the autoTls backend.

If a company wants to use its own root certificate instead of the auto-generated one, an intermediate certificate can be given to the secret operator. Currently, the secret operator only provides this intermediate certificate in volume mounts. Tools, like kcat, which do not use this certificate as a trust anchor, additionally need the root certificate. Therefore, the SecretClass CRD should be extended to allow defining additional certificates, as follows:

```yaml
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls-intermediate-cert
spec:
  backend:
    autoTls:
      ca:
        autoGenerate: false
        secret:
          name: intermediate-ca
          namespace: stackable-operators
      additionalTrustRoots:
        - secret:
            name: root-ca
            namespace: stackable-operators
```

The secrets of the additional trust roots can contain multiple entries. The keys are considered to be file names and the values their contents. The extension of a file name defines its content. According to https://en.wikipedia.org/wiki/X.509#Certificate_filename_extensions, the extension `.pem` denotes a stack of base64 encoded DER certificates, the extensions `.cer`, `.cert`, and `.crt` denote either a binary DER certificate or a stack of base64 encoded DER certificates. Other extensions can be supported in the future.
