### ISSUE TITLE
Type configuration

### ISSUE THREAD

**Issue by teozkr** [stackabletech/secret-operator#8]
We need to be able to map a secret request (Pod Volume) to the desired backend (such as #2, #3, #4). This mapping needs to be up to the cluster administrator, since this will depend on their secret provisioning policy (everything manual and takes 6 months, vs "I don't give a shit, just make it work").

Proposed example:

```yaml
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretType
metadata:
  name: tls-internal
spec:
  backend:
    tls:
      caSecret: tls-internal-ca
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretType
metadata:
  name: tls-manual
spec:
  backend:
    secret: {}
```
